<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CHR5D0E5" ignored="0" name="FunctionalTesting" tests="7" failures="1" timestamp="19 Nov 2019 11:08:39 GMT" time="0.839" errors="0">
  <testcase name="testCase1 on null(com.sampleproject.mavenSampleProject.AppTest)" time="0.006" classname="com.sampleproject.mavenSampleProject.AppTest"/>
  <testcase name="testCase4 on null(com.sampleproject.mavenSampleProject.AppTest)" time="0.0" classname="com.sampleproject.mavenSampleProject.AppTest">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.sampleproject.mavenSampleProject.AppTest.testCase4(AppTest.java:134)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testCase4 on null(com.sampleproject.mavenSampleProject.AppTest) -->
  <testcase name="testCase5 on null(com.sampleproject.mavenSampleProject.AppTest)" time="0.0" classname="com.sampleproject.mavenSampleProject.AppTest">
    <skipped/>
  </testcase> <!-- testCase5 on null(com.sampleproject.mavenSampleProject.AppTest) -->
  <testcase name="test_method_1 on null(com.sampleproject.mavenSampleProject.AppTest)" time="0.0" classname="com.sampleproject.mavenSampleProject.AppTest"/>
  <testcase name="test_method_2 on null(com.sampleproject.mavenSampleProject.AppTest)" time="0.38" classname="com.sampleproject.mavenSampleProject.AppTest"/>
  <testcase name="test_method_3 on null(com.sampleproject.mavenSampleProject.AppTest)" time="0.0" classname="com.sampleproject.mavenSampleProject.AppTest"/>
  <testcase name="testcase2 on null(com.sampleproject.mavenSampleProject.AppTest)" time="0.0" classname="com.sampleproject.mavenSampleProject.AppTest"/>
</testsuite> <!-- FunctionalTesting -->
